server:
  port: 8080
  shutdown: GRACEFUL
  servlet:
    context-path: /

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: workflow
  web:
    resources:
      static-locations: classpath:/static/
  freemarker:
    suffix: .ftl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow
    username: root
    password: 1111
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    database: MYSQL
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
  task:
    execution:
      pool:
        core-size: 2
        queue-capacity: 0
        max-size: 100
        keep-alive: 60s
      shutdown:
        await-termination: true
        await-termination-period: 10s
    scheduling:
      pool:
        size: 1
      shutdown:
        await-termination: true
        await-termination-period: 10s

camunda:
  bpm:
    deployment-resource-pattern: classpath:workflow/*.bpmn
    history-level: FULL